/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Godless Laboratories (https://sketchfab.com/noelnoir)
license: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
source: https://sketchfab.com/3d-models/neon-sun-moon-a0d6ad76fa4f494f82a8e92b8c1493a4
title: Neon Sun & Moon
*/

import { EffectComposer, SelectiveBloom } from '@react-three/postprocessing'
import { useGLTF } from "@react-three/drei";

export default function SunMoon(props) {
    const { nodes, materials } = useGLTF("./models/sunMoon.glb");

    return <>
        <group 
            ref={props.groupRef} 
            position={ props.position }
            dispose={null} 
            scale={ props.scale } 
        >
            <primitive object={nodes._rootJoint}/>
            {!props.showAlternate && 
            <>
                <mesh
                    ref={ props.sun1Ref }
                    name="Sun1"
                    geometry={nodes.Object_22.geometry}
                    material={materials["neon.sun1"]}
                    skeleton={nodes.Object_22.skeleton}
                    morphTargetDictionary={
                        nodes.Object_22.morphTargetDictionary
                    }
                    morphTargetInfluences={
                        nodes.Object_22.morphTargetInfluences
                    }
                />
                <mesh
                    ref={ props.moon1Ref }
                    name="Moon1"
                    geometry={nodes.Object_24.geometry}
                    material={materials["neon.moon1"]}
                    skeleton={nodes.Object_24.skeleton}
                    morphTargetDictionary={
                        nodes.Object_24.morphTargetDictionary
                    }
                    morphTargetInfluences={
                        nodes.Object_24.morphTargetInfluences
                    }
                />
            </>}
            {props.showAlternate && 
            <>
                <mesh
                    ref={ props.sun2Ref }
                    name="Sun2"
                    geometry={nodes.Object_26.geometry}
                    material={materials["neon.sun2"]}
                    skeleton={nodes.Object_26.skeleton}
                    morphTargetDictionary={
                        nodes.Object_26.morphTargetDictionary
                    }
                    morphTargetInfluences={
                        nodes.Object_26.morphTargetInfluences
                    }
                />
                <mesh
                    ref={ props.moon2Ref }
                    name="Moon2"
                    geometry={nodes.Object_28.geometry}
                    material={materials["neon.moon2"]}
                    skeleton={nodes.Object_28.skeleton}
                    morphTargetDictionary={
                        nodes.Object_28.morphTargetDictionary
                    }
                    morphTargetInfluences={
                        nodes.Object_28.morphTargetInfluences
                    }
                /> 
            </>}
        </group>
    </>
}

useGLTF.preload("./models/sunMoon.glb");